[package]
name = "sim-table-remote"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "SIM workspace package for sim table remote."
readme = "README.md"
publish = true
repository = "https://github.com/sim-nest/sim-agent-net"
homepage = "https://github.com/sim-nest/sim-agent-net"

[dependencies]
sim-citizen = { version = "0.1.0" }
sim-citizen-derive = { version = "0.1.0" }
sim-kernel = { version = "0.1.0" }
sim-lib-server = { version = "0.1.0", path = "../sim-lib-server" }
sim-table-core = { version = "0.1.0" }

[dev-dependencies]
sim-codec-binary = { version = "0.1.0" }
sim-table-db = { version = "0.1.0" }

[lints]
workspace = true
