[package]
name = "sim-mcp-server"
version = "0.1.2"
edition = "2024"
license = "MPL-2.0"
description = "Stdio MCP server bootloader for SIM."
readme = "README.md"
publish = true
repository = "https://github.com/sim-nest/sim-agent-net"
homepage = "https://github.com/sim-nest/sim-agent-net"

[dependencies]
sim-lib-mcp = { version = "0.1.1", features = ["serve"], path = "../sim-lib-mcp" }
sim-run-core = { version = "0.1.1" }



[lints]
workspace = true
